### ISSUE TITLE
Vixi Meals - MailChimp sign-up process

### ISSUE THREAD

**Issue by ashleydentino** [mamont77/vixi#45]
I need to create the functionality that allows people to sign up for user account while also simultaneously adding their first name and email to a MailChimp email list. 

Ideally I like to make the sign-up process as quick & easy as possible - only collecting first name, email and a password for their login. I'd like them to login using their email address as their username. They will need to be sent an email with their login details (I'd like to customize the language). Can we do it so they click a button on VixiMeals.com (while I'll provide) and they add their information in a simple pop-up window that works as well on a mobile as it does on a computer? 

The MailChimp list id is: 5a4fe46103
Please let me know what other info you need from me.

**Comment by ashleydentino** [comment]
Hey Ruslan - Can we also continue working on this? When people click the 'get free access now' button it is adding them to my mailchimp list, but it is not login them into the site and emailing them their login details. Is this an easy fix?

**Comment by mamont77** [comment]
1. Autologin after registration - completed.
2. The user still receives the email. He should to confirm his account. It's hard to turn off, but I can investigate this if you want.
![account details for ruslan at vixi meals - ruslan piskarev gmail 03-16-2015 09 26 40](https://cloud.githubusercontent.com/assets/970967/6662033/bf731f2e-cbbe-11e4-943d-9e6a6746d831.png)
3. This page (http://viximeals.com/recipesearch ) has been visible for the administrator role only. I added the "authenticated user" role to Access options here http://viximeals.com/admin/structure/views/view/recipe_search/edit/block_1.

Please check.

user rpiskarev@yandex.com - it's my test user.

**Comment by ashleydentino** [comment]
Hey Ruslan - I got this message when I was editing the email that gets sent to new users to activate their account. What does this mean? What do I need to do to fix it?

![screen shot 2015-03-16 at 2 30 11 pm](https://cloud.githubusercontent.com/assets/7060673/6673508/1356cf8e-cbea-11e4-9ba3-4f4cfd8b1b13.png)

**Comment by mamont77** [comment]
Just add to template a text like
Your login [user:name-raw].

The user can forget login. Without login, he can not login to the system.
But you can ignore this message, if you know what you're doing. Drupal is written warning, but it is not a error.
