### ISSUE TITLE
Homepage block

### ISSUE THREAD

**Issue by ashleydentino** [mamont77/vixi#54]
Hi Ruslan - I'm trying to add the frontpage: Ashley block to the left sidebar of my homepage. It's adding my image, but not the text that goes underneath it (as you can see here http://vixi.com/content/ayurvedic-remedies-colds-flu). Is there something else I need to do to get the text?

**Comment by mamont77** [comment]
This text there, but it is not visible.
![vixi feel alive - google chrome 03-16-2015 08 15 15](https://cloud.githubusercontent.com/assets/970967/6661426/c50349c8-cbb4-11e4-9254-bee54ccb1f76.png)
I will fix the css file.

**Comment by mamont77** [comment]
Fixed.

**Comment by ashleydentino** [comment]
Great thank you!
