### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by ashleydentino** [mamont77/vixi#55]
Hi Ruslan - Is there a way to quickly & easily add toggle functionality to Vixi like the one I'm using on Vixi Meals? 
http://viximeals.com/node/15#overlay-context=
http://viximeals.com/content/vixi-kitchen

**Comment by mamont77** [comment]
Yes. I can find a required piece of css & js code on http://getbootstrap.com/javascript/#collapse-example-accordion or viximeals.com and  implement the same functionality for vixi.

**Comment by mamont77** [comment]
Сan I make this task?

**Comment by ashleydentino** [comment]
Yes, please. Thank you.

**Comment by mamont77** [comment]
Hi Ashley,

Completed.
http://vixi.com/content/toggle-accortdion (this node is not published, visible the administrator only)

**Comment by ashleydentino** [comment]
thank you!

On Thu, Mar 19, 2015 at 4:54 AM, Ruslan <notifications@github.com> wrote:

> Hi Ashley,
>
> Completed.
> http://vixi.com/content/toggle-accortdion (this node is not published,
> visible the administrator only)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mamont77/vixi/issues/55#issuecomment-83426923>.
>



-- 
Ashley Dentino | www.vixi.com
email. ashley.dentino@gmail.com | cell. 602.315.9229

facebook <http://www.facebook.com/ashley.dentino> | instagram
<http://instagram.com/ashleydentino> | free newsletter
<http://vixi.us2.list-manage.com/subscribe?u=9298c5763dd416b1743c949fa&id=6e47921471>

........
Celebrate your thoughts; they become words. Celebrate your words; they
become actions.
 Celebrate your actions; they become habits. Celebrate your habits; they
become character.
Celebrate your character; for it becomes your destiny.

**Comment by ashleydentino** [comment]
One small issue - it seems like the font on the new pages that I create is smaller than the font on the rest of the site (like the blog post pages). Is this a quick fix?
http://vixi.com/content/vixi-kitchen

**Comment by mamont77** [comment]
This is a quick fix. Fixed. But it is applied globally for all pages entities.

**Comment by ashleydentino** [comment]
Thank you!

On Wed, Apr 1, 2015 at 2:11 PM, Ruslan <notifications@github.com> wrote:

> This is a quick fix. Fixed. But it is applied globally for all pages
> entities.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mamont77/vixi/issues/55#issuecomment-88580724>.
>



-- 
Ashley Dentino | www.vixi.com
email. ashley.dentino@gmail.com | cell. 602.315.9229

facebook <http://www.facebook.com/ashley.dentino> | instagram
<http://instagram.com/ashleydentino> | free newsletter
<http://vixi.us2.list-manage.com/subscribe?u=9298c5763dd416b1743c949fa&id=6e47921471>

........
Celebrate your thoughts; they become words. Celebrate your words; they
become actions.
 Celebrate your actions; they become habits. Celebrate your habits; they
become character.
Celebrate your character; for it becomes your destiny.

**Comment by ashleydentino** [comment]
Is there any way we can reduce the size of the text to the previous font on
this page only? http://www.vixi.com/content/testimonials

On Wed, Apr 1, 2015 at 2:42 PM, Ashley Dentino <ashley.dentino@gmail.com>
wrote:

> Thank you!
>
> On Wed, Apr 1, 2015 at 2:11 PM, Ruslan <notifications@github.com> wrote:
>
>> This is a quick fix. Fixed. But it is applied globally for all pages
>> entities.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mamont77/vixi/issues/55#issuecomment-88580724>.
>>
>
>
>
> --
> Ashley Dentino | www.vixi.com
> email. ashley.dentino@gmail.com | cell. 602.315.9229
>
> facebook <http://www.facebook.com/ashley.dentino> | instagram
> <http://instagram.com/ashleydentino> | free newsletter
> <http://vixi.us2.list-manage.com/subscribe?u=9298c5763dd416b1743c949fa&id=6e47921471>
>
> ........
> Celebrate your thoughts; they become words. Celebrate your words; they
> become actions.
>  Celebrate your actions; they become habits. Celebrate your habits; they
> become character.
> Celebrate your character; for it becomes your destiny.
>



-- 
Ashley Dentino | www.vixi.com
email. ashley.dentino@gmail.com | cell. 602.315.9229

facebook <http://www.facebook.com/ashley.dentino> | instagram
<http://instagram.com/ashleydentino> | free newsletter
<http://vixi.us2.list-manage.com/subscribe?u=9298c5763dd416b1743c949fa&id=6e47921471>

........
Celebrate your thoughts; they become words. Celebrate your words; they
become actions.
 Celebrate your actions; they become habits. Celebrate your habits; they
become character.
Celebrate your character; for it becomes your destiny.

**Comment by mamont77** [comment]
Hi Ashley,

It possible, I added a new rule (exception) for this page. You can send me list of other pages in future.

**Comment by ashleydentino** [comment]
Thank you Ruslan! Appreciate how quickly you always respond.
