### ISSUE TITLE
[vixi] podcast implementation 

### ISSUE THREAD

**Issue by mamont77** [mamont77/vixi#56]
Specs:
https://www.apple.com/itunes/podcasts/specs.html
http://www.apple.com/itunes/podcasts/creatorfaq.html
https://blog.breadncup.com/2013/03/31/how-to-make-a-podcasts-in-itunes/
https://phobos.apple.com/WebObjects/MZFinance.woa/wa/publishPodcast (https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/publishPodcast)

http://castfeedvalidator.com/?url=http://vixi.com/itunes-podcast.xml
http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fvixi.com%2Fitunes-podcast.xml

http://vixi.com/itunes-podcast.xml

**Comment by mamont77** [comment]
@ashleydentino 

I need your help.

Prepare the necessary pictures.

* Path to the image to be used as the artwork for your feed, for example sites/default/files/AllAboutEverything.jpg. Allowed image formats are GIF, JPEG or PNG. Maximum image width is 144 pixels, maximum height 400 pixels.
* Path to the image to be used as the artwork for your podcast, for example sites/default/files/AllAboutEverything.jpg. iTunes prefers square .jpg images that are at least 600 x 600 pixels. iTunes supports images in JPEG and PNG formats with a RGB color space (CMYK is not supported). If the tag is not present, iTunes will use the contents of the RSS <image> tag.

(you can send me images to skype and i will upload it by ftp)

then

1. Please go to http://vixi.com/node/add/itunes-podcast and create a few podcasts (optional because we have two temporary podcast).
2. Go to http://vixi.com/admin/build/views/edit/itunes_podcast and edit the fields that you understand. (look a screensnap)
3. Check that there are no errors http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fvixi.com%2Fitunes-poscast.xml. Or I'll fix it later.

You can see a podcast in browser http://vixi.com/itunes-poscast.xml + http://vixi.com/content/first-poscast.

then let me know :-)

**Comment by ashleydentino** [comment]
Ok, I have added as much info as I could and also upload the image. Thank you! Please advise me on what to do next.

**Comment by mamont77** [comment]
Look good to me.

Now please add a several podcast.
http://vixi.com/node/add/itunes-podcast

Then you can delete
http://vixi.com/content/first-poscast
http://vixi.com/content/second-podcast
http://vixi.com/content/third-podcast

Then in iTunes, submit your RSS podcast feed URL (http://vixi.com/itunes-podcast.xml) to the iTunes Store (https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/publishPodcast).

**Comment by ashleydentino** [comment]
Hey Ruslan - I'm getting this error when I submit my podcast.

On Wed, Mar 18, 2015 at 1:25 AM, Ruslan <notifications@github.com> wrote:

> Look good to me.
>
> Now please add a several podcast.
> http://vixi.com/node/add/itunes-podcast
>
> Then you can delete
> http://vixi.com/content/first-poscast
> http://vixi.com/content/second-podcast
> http://vixi.com/content/third-podcast
>
> Then in iTunes, submit your RSS podcast feed URL (
> http://vixi.com/itunes-podcast.xml) to the iTunes Store (
> https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/publishPodcast).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mamont77/vixi/issues/56#issuecomment-82747910>.
>



-- 
Ashley Dentino | www.vixi.com
email. ashley.dentino@gmail.com | cell. 602.315.9229

facebook <http://www.facebook.com/ashley.dentino> | instagram
<http://instagram.com/ashleydentino> | free newsletter
<http://vixi.us2.list-manage.com/subscribe?u=9298c5763dd416b1743c949fa&id=6e47921471>

........
Celebrate your thoughts; they become words. Celebrate your words; they
become actions.
 Celebrate your actions; they become habits. Celebrate your habits; they
become character.
Celebrate your character; for it becomes your destiny.

**Comment by ashleydentino** [comment]
I tried to upload this image for the cover
art: /sites/default/files/vixishowcoverart.jpg

Could the issue be that the field only allows 144 x 400 for the image size
and iTunes requires minimum of 1400 x 1400?

On Tue, Apr 7, 2015 at 11:42 PM, Ashley Dentino <ashley.dentino@gmail.com>
wrote:

> Hey Ruslan - I'm getting this error when I submit my podcast.
>
> On Wed, Mar 18, 2015 at 1:25 AM, Ruslan <notifications@github.com> wrote:
>
>> Look good to me.
>>
>> Now please add a several podcast.
>> http://vixi.com/node/add/itunes-podcast
>>
>> Then you can delete
>> http://vixi.com/content/first-poscast
>> http://vixi.com/content/second-podcast
>> http://vixi.com/content/third-podcast
>>
>> Then in iTunes, submit your RSS podcast feed URL (
>> http://vixi.com/itunes-podcast.xml) to the iTunes Store (
>> https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/publishPodcast).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mamont77/vixi/issues/56#issuecomment-82747910>.
>>
>
>
>
> --
> Ashley Dentino | www.vixi.com
> email. ashley.dentino@gmail.com | cell. 602.315.9229
>
> facebook <http://www.facebook.com/ashley.dentino> | instagram
> <http://instagram.com/ashleydentino> | free newsletter
> <http://vixi.us2.list-manage.com/subscribe?u=9298c5763dd416b1743c949fa&id=6e47921471>
>
> ........
> Celebrate your thoughts; they become words. Celebrate your words; they
> become actions.
>  Celebrate your actions; they become habits. Celebrate your habits; they
> become character.
> Celebrate your character; for it becomes your destiny.
>



-- 
Ashley Dentino | www.vixi.com
email. ashley.dentino@gmail.com | cell. 602.315.9229

facebook <http://www.facebook.com/ashley.dentino> | instagram
<http://instagram.com/ashleydentino> | free newsletter
<http://vixi.us2.list-manage.com/subscribe?u=9298c5763dd416b1743c949fa&id=6e47921471>

........
Celebrate your thoughts; they become words. Celebrate your words; they
become actions.
 Celebrate your actions; they become habits. Celebrate your habits; they
become character.
Celebrate your character; for it becomes your destiny.

**Comment by mamont77** [comment]
Hey Ashley,

Cool podcast)))
Can you copy paste error or screensnap? 
I can try add podcast, but in this case I will become the owner in AppleID.

**Comment by ashleydentino** [comment]
Thanks for the quick response and the kind words.

I'll add the podcast once we get this ironed out.

![screen shot 2015-04-07 at 11 41 11 pm](https://cloud.githubusercontent.com/assets/7060673/7038818/5dd54912-dd85-11e4-8067-20b57db53819.png)

**Comment by ashleydentino** [comment]
Also, is there a way I'll be able to add a player inside an actual post, like on this page? (Right now the image under the podcast sessions links to the podcast, which opens up on a new page.) It would be great to have the option to either listen to it in it's own window or listen to it right on the page: http://www.vixi.com/content/vixi-kitchen-ep-1

**Comment by mamont77** [comment]
>>I'll add the podcast once we get this ironed out.

Try now!

>>is there a way I'll be able to add a player inside an actual post

Yes, we will make the player later.

**Comment by ashleydentino** [comment]
It worked! Thanks.

Ok, let's talk about the player before we start working on it. Please let me know the first step we need to take.

**Comment by mamont77** [comment]
I found some modules.
https://www.drupal.org/project/audiofield
https://www.drupal.org/project/jplayer
https://www.drupal.org/project/mp3player
I can try any there http://vixi.com/content/vixi-kitchen-ep-1-0.

Another method. I can make a widget (ready html code with design) and you'll be able to add a podcast to any page by changing the link to mp3.

I will be glad to see your ideas too.

**Comment by mamont77** [comment]
Another link, it does not require any changes to your website.
https://widgets.itunes.apple.com/builder/ (https://url.odesk.com/_013XKJ1XDrKzzzBn6JEG8_THQXCQHqcg60)

**Comment by ashleydentino** [comment]
Ok, I'll give these a look later today. Thanks.

For some reason, the teaser for this post is not showing up on my homepage: http://www.vixi.com/content/vixi-kitchen-ep-1

What do I need to do to fix it?

**Comment by mamont77** [comment]
>>For some reason, the teaser for this post is not showing up on my homepage: http://www.vixi.com/content/vixi-kitchen-ep-1

I can see on page # 2.

![1](https://cloud.githubusercontent.com/assets/970967/7060495/a41bcbd4-de8a-11e4-8149-f305c23f11ca.png)

![2](https://cloud.githubusercontent.com/assets/970967/7060497/aa40661e-de8a-11e4-9abe-f2218e7275df.png)

**Comment by mamont77** [comment]
Congratulations. I can see it. :kissing_heart:
![itunes 04-10-2015 01 01 36](https://cloud.githubusercontent.com/assets/970967/7077947/9ab801a0-df1d-11e4-8e63-667bb7cb32e0.png)

Can we close this task and open one another about the player?

**Comment by ashleydentino** [comment]
Thank you! Yes, we can.

On Thu, Apr 9, 2015 at 6:08 PM, Ruslan <notifications@github.com> wrote:

> Congratulations. I can see it. [image: :kissing_heart:]
> [image: itunes 04-10-2015 01 01 36]
> <https://cloud.githubusercontent.com/assets/970967/7077947/9ab801a0-df1d-11e4-8e63-667bb7cb32e0.png>
>
> Can we close this task and open one another about the player?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mamont77/vixi/issues/56#issuecomment-91368473>.
>



-- 
Ashley Dentino | www.vixi.com
email. ashley.dentino@gmail.com | cell. 602.315.9229

facebook <http://www.facebook.com/ashley.dentino> | instagram
<http://instagram.com/ashleydentino> | free newsletter
<http://vixi.us2.list-manage.com/subscribe?u=9298c5763dd416b1743c949fa&id=6e47921471>

........
Celebrate your thoughts; they become words. Celebrate your words; they
become actions.
 Celebrate your actions; they become habits. Celebrate your habits; they
become character.
Celebrate your character; for it becomes your destiny.
